name: Test dependencies for security issues with Snyk

on: 
  push:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  dependencies-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.8
    - name: Show environment
      run: | 
        python --version
        pip --version
    - uses: snyk/actions/setup@master
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test dependencies with Snyk
      run: |
        snyk test --severity-threshold=critical || exit 1
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
    - name: Monitor dependencies for security issues with Snyk
      run: snyk monitor
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
