name: Test dependencies for security issues with Snyk

on: 
  push:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  dependencies-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.8
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
    - name: Show environment
      run: | 
        python --version
        pip --version
        poetry --version
    - uses: snyk/actions/setup@master
    - name: Install Python dependencies with Poetry
      working-directory: pygoat
      run: |
        pwd
        poetry install -v
    - name: Run tests
      run: poetry run pytest
    - name: Test dependencies with Snyk
      run: snyk test
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
    - name: Monitor dependencies for security issues with Snyk
      run: snyk monitor
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
